#!/bin/sh
#
# Adisp main program - sequentially runs plugins from the list 
# and display their output to LCD - divided into two-line messages
#
# Author: Adam Benda, 2016
# License: MIT 
# https://github.com/adasek/ameas/
#
#
#

source /etc/adisp.conf

while read -r line || [ -n "$line" ]
do
             
 #remove comments and trim
 cmd=`echo "$line" | sed -e 's/#.*$//g' -e 's/^[\r\n\t ]*//' -e 's/[\r\n\t ]*$//'`
 
#no need to disallow directory traversal.
#(passing "../../../sbin/reboot" as $cmd)   

#Needs to be considered if plugins.txt are generated by user/remotely

if [ "" = "$cmd" ]
 then
  #empty line
  continue;
elif [ -r "$PLUGIN_DIR"/"$cmd" ]
 then
  #there is some readable script
  output=`"$PLUGIN_DIR"/"$cmd" 2>/tmp/err$$`
  retCode=$?
   if [ $retCode -ne 0 ]
    then
    #error returned   
     echo "WARNING ("`date`")$cmd failed with status $retCode" >&2 
     echo "Error message:" >&2   
     echo "$output" >&2
     echo "-------" >&2
     continue; #do not display this
    fi
    
  outputLines=`echo "$output"|wc -l`
  #first two lines from output
  while [ "$output" != "" ]
   do
   firstLine=`echo "$output"|head -n 1` #get first line
   secondLine=`echo "$output"|head -n 2|tail -n 1` #get second line
    
    #show on display
    if $LCD_BIN 2 "$firstLine                    " "$secondLine                    "
       then
       :
       else
        echo "ERROR ("`date`") Display set failed." >&2
        exit 5
       fi
        
    output=`echo "$output"|tail -n +3` #remove first two lines   
    sleep $TIME_SHOW
   done 
  
  
else
  echo "Script $cmd does not exist or is not readable" >&2
fi 


done < "$PLUGIN_LIST"

