#!/bin/sh
#See: https://forum.openwrt.org/viewtopic.php?id=59338

echo "Adding to crontab"
mkdir -p /etc/crontabs

grep -sq '/sbin/measure.sh' /etc/crontabs/root || echo '* * * * * /sbin/measure.sh 2>> /var/log/measure.err.log; /sbin/upload.sh 2>> /var/log/upload.err.log' >> /etc/crontabs/root

/etc/init.d/cron reload